"""empty message

Revision ID: e935494f6bab
Revises: 8500f5ec6c45
Create Date: 2017-07-17 16:55:03.296629

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e935494f6bab'
down_revision = '8500f5ec6c45'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_forms', sa.Column('field_identifier', sa.String(), nullable=False))
    op.add_column('custom_forms', sa.Column('form', sa.String(), nullable=False))
    op.add_column('custom_forms', sa.Column('is_fixed', sa.Boolean(), nullable=True))
    op.add_column('custom_forms', sa.Column('is_included', sa.Boolean(), nullable=True))
    op.add_column('custom_forms', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.add_column('custom_forms', sa.Column('type', sa.String(), nullable=False))
    op.create_unique_constraint('custom_form_identifier', 'custom_forms', ['event_id', 'field_identifier', 'form'])
    op.drop_column('custom_forms', 'speaker_form')
    op.drop_column('custom_forms', 'session_form')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_forms', sa.Column('session_form', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('custom_forms', sa.Column('speaker_form', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('custom_form_identifier', 'custom_forms', type_='unique')
    op.drop_column('custom_forms', 'type')
    op.drop_column('custom_forms', 'is_required')
    op.drop_column('custom_forms', 'is_included')
    op.drop_column('custom_forms', 'is_fixed')
    op.drop_column('custom_forms', 'form')
    op.drop_column('custom_forms', 'field_identifier')
    # ### end Alembic commands ###
